format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$cmd_duration\
$username\
$hostname\
$line_break\
${custom.virtual_or_conda_env}\
$character"""

[directory]
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_commit]
style = "bright-black"
tag_disabled = false
tag_symbol = ' '

[git_status]
# I don't use $untracked in format because I often do not care that much about
# untracked files
format = "[[(*$conflicted$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[username]
format = '[$user]($style)'
style_user = "bright-black"

[hostname]
format='[@$hostname]($style)'
style = "bright-black"

[custom.virtual_or_conda_env]
# starship has python for virtual environment and conda for conda environment
# but to combine both it seems like I need a custom command
command = "[[ -n $VIRTUAL_ENV ]] && echo $(basename $VIRTUAL_ENV) || echo $CONDA_DEFAULT_ENV"
when = true
style = "bright-black"
